spring:
  datasource:
    url: jdbc:h2:mem:ecommercedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"

  security:
    enable-csrf: false

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: your-256-bit-secret-key-here
  expiration: 86400000 # 24 hours in milliseconds

app:
  discount:
    time-based:
      enabled: true
      start-time: "10:00"
      end-time: "18:00"
      percentage: 10
    random-order:
      percentage: 50
    frequent-customer:
      min-orders: 5
      percentage: 5